---

- hosts: all
  become: true
  tasks:
    - name: Update packages list
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'

    - name: List packages to remove (1/2)
#      shell: apt -s -V -u upgrade
      shell: apt-get autoremove -s
      register: removable
      changed_when: False
      when: ansible_os_family == 'Debian'

    - name: List packages to remove (2/2)
      debug: msg="{{ removable.stdout_lines | count }} packages to remove ({{ removable.stdout_lines | join(', ') }})"
      when: (ansible_os_family == 'Debian' and removable.stdout_lines)
