---

- hosts: debian
  become: true
  tasks:
    - name: Update packages list
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'

    - name: List packages to upgrade (1/2)
#      shell: aptitude -q -F%p --disable-columns search "~U"
      shell: apt -s -V -u dist-upgrade
#      shell: apt-get -qq -s dist-upgrade
      register: updates
      changed_when: False
      when: ansible_os_family == 'Debian'

    - name: List packages to upgrade (2/2)
      debug: msg="{{ updates.stdout_lines | count }} packages to upgrade ({{ updates.stdout_lines | join(', ') }})"
#      debug: msg="{{ updates.stdout_lines | join(', ') }}" 
      when: (ansible_os_family == 'Debian' and updates.stdout_lines)
