---
- hosts: localhost
  tasks:
   - name: Create snapshot
     vmware_guest_snapshot:
       hostname: 192.168.0.50
       username: root
       password: "@pro{voc*"
       datacenter: 192.168.0.50
       folder: /vm
       name: nakivobackup
       state: present
       snapshot_name: snap1
       description: snap1_description
#  delegate_to: localhost
