---
- name: Ansible Find Example
  hosts: debian
  tasks:
   - name : Find files older than 30 days
     become: yes
     find:
       paths: /var/log
       patterns: 'toto.txt'
#       age: 30d
#       age_stamp: mtime
     register: output

   - name: Delete the files matching
     become: yes
     file:
       path: "{{item.path}}"
       state: absent
     with_items: "{{ output.files }}"
